"""add_migration_models

Revision ID: 85a84fcaf661
Revises: 93a8200d34f0
Create Date: 2026-04-09 01:13:12.807972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a84fcaf661'
down_revision: Union[str, None] = '93a8200d34f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)
    if 'migrations' not in insp.get_table_names():
        op.create_table('migrations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('source_url', sa.String(length=500), nullable=False),
        sa.Column('target_section_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('total_pages', sa.Integer(), nullable=False),
        sa.Column('completed_pages', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('tree_json', sa.Text(), nullable=True),
        sa.Column('page_id_map_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_section_id'], ['sections.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'migration_pages' not in insp.get_table_names():
        op.create_table('migration_pages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('migration_id', sa.Integer(), nullable=False),
        sa.Column('source_url', sa.String(length=500), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('target_page_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('html_content', sa.Text(), nullable=True),
        sa.Column('markdown_content', sa.Text(), nullable=True),
        sa.Column('drive_html_content', sa.Text(), nullable=True),
        sa.Column('section_node_path', sa.String(length=1000), nullable=False),
        sa.Column('display_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['migration_id'], ['migrations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_page_id'], ['pages.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('migration_id', 'source_url', name='uq_migration_page_url')
        )
        op.create_index('ix_migration_pages_migration_id_status', 'migration_pages', ['migration_id', 'status'], unique=False)
    
    with op.batch_alter_table('organizations') as batch:
        batch.alter_column('hierarchy_mode', existing_type=sa.VARCHAR(length=20), nullable=False)
        batch.alter_column('show_toc', existing_type=sa.BOOLEAN(), nullable=False)

    with op.batch_alter_table('pages') as batch:
        batch.alter_column('slug_locked', existing_type=sa.BOOLEAN(), nullable=False)
        batch.alter_column('hide_toc', existing_type=sa.BOOLEAN(), nullable=False)
        batch.alter_column('full_width', existing_type=sa.BOOLEAN(), nullable=False)
        batch.create_index('ix_pages_org_visibility_override', ['organization_id', 'visibility_override'], unique=False)
        batch.create_unique_constraint('uq_page_slug_per_org', ['organization_id', 'slug'])

    with op.batch_alter_table('sections') as batch:
        batch.alter_column('visibility', existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections') as batch:
        batch.alter_column('visibility', existing_type=sa.VARCHAR(length=20), nullable=True)

    with op.batch_alter_table('pages') as batch:
        batch.drop_constraint('uq_page_slug_per_org', type_='unique')
        batch.drop_index('ix_pages_org_visibility_override')
        batch.alter_column('full_width', existing_type=sa.BOOLEAN(), nullable=True)
        batch.alter_column('hide_toc', existing_type=sa.BOOLEAN(), nullable=True)
        batch.alter_column('slug_locked', existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table('organizations') as batch:
        batch.alter_column('show_toc', existing_type=sa.BOOLEAN(), nullable=True)
        batch.alter_column('hierarchy_mode', existing_type=sa.VARCHAR(length=20), nullable=True)

    op.drop_index('ix_migration_pages_migration_id_status', table_name='migration_pages')
    op.drop_table('migration_pages')
    op.drop_table('migrations')
    # ### end Alembic commands ###
