"""add_organization_and_9_new_models

Revision ID: aee3a6ce7d18
Revises: e44ff52b441e
Create Date: 2026-02-23 23:57:16.478051
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee3a6ce7d18'
down_revision: Union[str, None] = 'e44ff52b441e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('custom_docs_domain', sa.String(length=255), nullable=True),
    sa.Column('subdomain', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('accent_color', sa.String(length=50), nullable=True),
    sa.Column('font_heading', sa.String(length=100), nullable=True),
    sa.Column('font_body', sa.String(length=100), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('hero_title', sa.String(length=500), nullable=True),
    sa.Column('hero_description', sa.Text(), nullable=True),
    sa.Column('show_search_on_landing', sa.Boolean(), nullable=False),
    sa.Column('show_featured_projects', sa.Boolean(), nullable=False),
    sa.Column('custom_links', sa.Text(), nullable=True),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('openapi_spec_json', sa.Text(), nullable=True),
    sa.Column('openapi_spec_url', sa.String(length=500), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('drive_permissions_last_synced_at', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('domain_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('ssl_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('invited_by_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('semver_major', sa.Integer(), nullable=True),
    sa.Column('semver_minor', sa.Integer(), nullable=True),
    sa.Column('semver_patch', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_version_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('content_html_encrypted', sa.Text(), nullable=True),
    sa.Column('content_text_encrypted', sa.Text(), nullable=True),
    sa.Column('headings_encrypted', sa.Text(), nullable=True),
    sa.Column('published_content_html_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('project_version_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('content_html', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('published_content_html', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('content_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('published_content_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('video_title', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('display_order', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('google_modified_at', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'project_versions', ['project_version_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'])
    op.add_column('projects', sa.Column('drive_parent_id', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(length=50), nullable=False, server_default='internal'))
    op.add_column('projects', sa.Column('is_published', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('show_version_switcher', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'projects', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'parent_id')
    op.drop_column('projects', 'organization_id')
    op.drop_column('projects', 'show_version_switcher')
    op.drop_column('projects', 'is_published')
    op.drop_column('projects', 'visibility')
    op.drop_column('projects', 'drive_parent_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'google_modified_at')
    op.drop_column('documents', 'display_order')
    op.drop_column('documents', 'video_title')
    op.drop_column('documents', 'video_url')
    op.drop_column('documents', 'published_content_id')
    op.drop_column('documents', 'content_id')
    op.drop_column('documents', 'published_content_html')
    op.drop_column('documents', 'content_html')
    op.drop_column('documents', 'is_published')
    op.drop_column('documents', 'owner_id')
    op.drop_column('documents', 'topic_id')
    op.drop_column('documents', 'project_version_id')
    op.drop_column('documents', 'project_id')
    op.drop_table('document_cache')
    op.drop_table('topics')
    op.drop_table('project_versions')
    op.drop_table('project_members')
    op.drop_table('invitations')
    op.drop_table('domains')
    op.drop_table('audit_logs')
    op.drop_table('org_roles')
    op.drop_table('join_requests')
    op.drop_table('organizations')
    # ### end Alembic commands ###
